### PR TITLE
Fix a bug where hyperlinks displayed in blue

### LINKED ISSUE #19: Structure Field displays hyperlinks in a dark blue text color
This makes them hard to read in the dark theme of the app.

### PR DESCRIPTION
**Pull request by Rion-Kaneshiro**
Resolves: #19

### CODE REVIEW

File: BunPuro/UI/StructureInfoCell.swift [hunk 1]
```diff
@@ -17,7 +17,14 @@ final class StructureInfoCell: UITableViewCell {
             return descriptionLabel?.attributedText
         }
         set {
-            descriptionLabel?.attributedText = newValue
+            guard let string = newValue?.string else { return }
+
+            let linkAttributes: [NSAttributedString.Key: Any] = [
+                .foregroundColor: UIColor.white,
+                NSAttributedString.Key.underlineColor: UIColor.clear
```
Comment (Jeehut) [inline BunPuro/UI/StructureInfoCell.swift:24]: Why a full declaration here?

Comment (Rion-Kaneshiro) [reply BunPuro/UI/StructureInfoCell.swift:24]: An oversight ._.
